set nocompatible
set noswapfile
set nobackup
let $LANG='en'
set lm=en
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set encoding=utf-8
set columns=120
set lines=35
set go=
"set guifont=consolas:h11
set guifont=DejaVu_Sans_Mono_for_Powerline:h10:cANSI
set cursorline

"显示布局
set laststatus=2
set number
"set numberwidth=5
set softtabstop=2
set shiftwidth=2
set autoindent

syntax enable
let g:solarized_menu=0
colorscheme solarized

"
"自定义按键（与插件无关）
"
"map <C-w> :tab close<CR>
"map <C-n> :tab new<CR>

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

"
"这里是NERDTree的必要配置
"
map <F2> :silent! NERDTreeToggle<CR>
let NERDTreeWinPos="right"   "将窗口显示在右边
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '▾'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeDirArrowCollapsible = '▾'

"
"这里是gvimfullscreen的配置：
"
if has('gui_running') && has("win32")
    map <F11> :call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<CR>
endif

"
"这里是vimtweak的配置
"
au GUIEnter * call libcallnr("vimtweak.dll", "SetAlpha", 240)

"
"as3字典文件；
"
"au FileType actionscript call AddAS3Dic()
"function AddAS3Dic()
"	set dictionary-=$VIM/vimfiles/dic/as3_dic.txt dictinary+=$VIM/vimfiles/dic/ad3_dic.txt
"	set complete-=k complete+=k
"endfunction


"这里是vim-powerline的配置；（目前用vim-airline代替powerline）
"let g:Powerline_symbols = 'fancy'
"set t_Co=256
"set fillchars+=stl:\ ,stlnc:\
"let g:Powerline_mode_V="V·LINE"
"let g:Powerline_mode_cv="V·BLOCK"
"let g:Powerline_mode_S="S·LINE"
"let g:Powerline_mode_cs="S·BLOCK"

"
"这里是vim-airline的配置
"
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
set t_Co=256
let g:airline_theme = 'light'
"let g:airline#extensions#tabline#enabled = 1
let g:airline_detect_whitespace = 0
let g:airline_powerline_fonts = 1
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '♣'
let g:airline_symbols.linenr = '☺'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '☻'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

"
"taglist配置
"
let Tlist_Show_One_File=1    "只显示当前文件的tags
let Tlist_WinWidth=40        "设置taglist宽度
let Tlist_Exit_OnlyWindow=1  "tagList窗口是最后一个窗口，则退出Vim
let Tlist_Use_Right_Window=0 "在Vim窗口右侧显示taglist窗口
map <F8> :silent! TlistToggle<CR>
